# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvstore.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nKvResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t2O\n\x07KvStore\x12!\n\x03Set\x12\x0b.SetRequest\x1a\x0b.KvResponse\"\x00\x12!\n\x03Get\x12\x0b.GetRequest\x1a\x0b.KvResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETREQUEST._serialized_start=17
  _SETREQUEST._serialized_end=57
  _KVRESPONSE._serialized_start=59
  _KVRESPONSE._serialized_end=99
  _GETREQUEST._serialized_start=101
  _GETREQUEST._serialized_end=126
  _KVSTORE._serialized_start=128
  _KVSTORE._serialized_end=207
# @@protoc_insertion_point(module_scope)
